import type { Metadata } from "next";
import { headers } from "next/headers";
import "./pavel.css";
import { PricingProvider } from "@/components/pavel/PricingProvider";
import { COUNTRIES } from "@/components/pavel/countries";
import { loadWorkshopState } from "@/lib/pavel/loadSchedule";
import {
  countryFromGeo,
  countryFromParam,
} from "@/components/pavel/pricing";
import { Navbar } from "@/components/pavel/sections/Navbar";
import { Hero } from "@/components/pavel/sections/Hero";
import { Instructor } from "@/components/pavel/sections/Instructor";
import { Testimonials } from "@/components/pavel/sections/Testimonials";
import { Problem } from "@/components/pavel/sections/Problem";
import { Shift } from "@/components/pavel/sections/Shift";
import { Proof } from "@/components/pavel/sections/Proof";
import { Curriculum } from "@/components/pavel/sections/Curriculum";
import { Audience } from "@/components/pavel/sections/Audience";
import { Deliverables } from "@/components/pavel/sections/Deliverables";
import { CertificateShowcase } from "@/components/pavel/sections/CertificateShowcase";
import { Pricing } from "@/components/pavel/sections/Pricing";
import { FAQ } from "@/components/pavel/sections/FAQ";
import { FinalCTA } from "@/components/pavel/sections/FinalCTA";
import { Footer } from "@/components/pavel/sections/Footer";
import { MobileStickyBanner } from "@/components/pavel/sections/MobileStickyBanner";

export const metadata: Metadata = {
  title:
    "Semantic SEO Workshop with Pavel Klimakov. Stop Guessing What Google Wants.",
  description:
    "A 3-hour live workshop on the Semantic SEO framework. Learn how Google actually evaluates content, build topical authority, and rank without out-spending competitors on links. $99. Live on Zoom.",
  openGraph: {
    title: "Semantic SEO Workshop with Pavel Klimakov",
    description:
      "The system that engineers relevance. A 3-hour live intensive on entities, topical authority, and reading Google the way it reads the web.",
    type: "website",
    url: "/pavel",
    // og:image is generated by app/pavel/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Semantic SEO Workshop with Pavel Klimakov",
    description:
      "The system that engineers relevance. A 3-hour live intensive on entities, topical authority, and reading Google the way it reads the web.",
    // twitter falls back to the generated opengraph-image
  },
};

export default async function PavelWorkshopPage({
  searchParams,
}: {
  searchParams: Promise<{ country?: string }>;
}) {
  // Auto-detect the visitor's country from Vercel's edge geo header so the
  // correct price is server-rendered on the single /pavel URL. `?country=in`
  // (or `rest`) overrides detection for local dev and QA of both variants.
  const [{ country: countryParam }, headerList, workshop] = await Promise.all([
    searchParams,
    headers(),
    // The active session's date, time and whether it is selling, so a new
    // cohort (or a close) needs no deploy.
    loadWorkshopState(),
  ]);
  const geoCode = headerList.get("x-vercel-ip-country");
  const initialCountry =
    countryFromParam(countryParam) ?? countryFromGeo(geoCode);

  // Keep the SPECIFIC country too, not just the pricing region, so the checkout
  // can pre-select it. countryFromGeo collapses everything to IN or REST, which
  // cannot name a country. Absent locally and on the droplet, where the edge geo
  // header does not exist.
  const detected = COUNTRIES.find((c) => c.code === geoCode?.toUpperCase());
  const detectedCountryName = detected?.name ?? "";

  // A first guess at the viewer's timezone, so the server-rendered HTML already
  // shows their local time instead of IST. The browser's own zone replaces it
  // on hydration: it is exact where this is only country-level (one zone for
  // all of the US), but it does not exist until the page is running.
  const detectedTimeZone = detected?.tz ?? "";

  return (
    <PricingProvider
      initialCountry={initialCountry}
      detectedCountryName={detectedCountryName}
      detectedTimeZone={detectedTimeZone}
      schedule={workshop.schedule}
      registration={workshop.registration}
    >
      <div className="min-h-screen bg-background-soft text-primary tnum">
        <Navbar />
        <Hero />
        <Instructor />
        <Proof />
        <Problem />
        <Curriculum />
        <Shift />
        <Testimonials />
        <Audience />
        <Deliverables />
        <CertificateShowcase />
        <Pricing />
        <FAQ />
        <FinalCTA />
        <Footer />
        <MobileStickyBanner />
      </div>
    </PricingProvider>
  );
}
