/**
 * Full ISO 3166 country list used by the Pavel checkout modal's country
 * selector. `code` is the ISO 3166-1 alpha-2 code; `name` is the display label;
 * `tz` is a representative IANA timezone used to convert the fixed workshop
 * start instant (WORKSHOP.startUtc) into the attendee's local time.
 *
 * NOTE: for countries that span multiple zones (US, Canada, Australia, Russia,
 * Brazil, …) `tz` is the capital / most-populous zone — a sensible default, not
 * a per-user exact zone. Formatting is wrapped in a try/catch at the call site,
 * so an unsupported zone falls back to the default IST label rather than throwing.
 */
export interface Country {
  code: string;
  name: string;
  tz: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", tz: "Asia/Kabul" },
  { code: "AX", name: "Åland Islands", tz: "Europe/Helsinki" },
  { code: "AL", name: "Albania", tz: "Europe/Tirane" },
  { code: "DZ", name: "Algeria", tz: "Africa/Algiers" },
  { code: "AS", name: "American Samoa", tz: "Pacific/Pago_Pago" },
  { code: "AD", name: "Andorra", tz: "Europe/Andorra" },
  { code: "AO", name: "Angola", tz: "Africa/Luanda" },
  { code: "AI", name: "Anguilla", tz: "America/Anguilla" },
  { code: "AQ", name: "Antarctica", tz: "Antarctica/McMurdo" },
  { code: "AG", name: "Antigua and Barbuda", tz: "America/Antigua" },
  { code: "AR", name: "Argentina", tz: "America/Argentina/Buenos_Aires" },
  { code: "AM", name: "Armenia", tz: "Asia/Yerevan" },
  { code: "AW", name: "Aruba", tz: "America/Aruba" },
  { code: "AU", name: "Australia", tz: "Australia/Sydney" },
  { code: "AT", name: "Austria", tz: "Europe/Vienna" },
  { code: "AZ", name: "Azerbaijan", tz: "Asia/Baku" },
  { code: "BS", name: "Bahamas", tz: "America/Nassau" },
  { code: "BH", name: "Bahrain", tz: "Asia/Bahrain" },
  { code: "BD", name: "Bangladesh", tz: "Asia/Dhaka" },
  { code: "BB", name: "Barbados", tz: "America/Barbados" },
  { code: "BY", name: "Belarus", tz: "Europe/Minsk" },
  { code: "BE", name: "Belgium", tz: "Europe/Brussels" },
  { code: "BZ", name: "Belize", tz: "America/Belize" },
  { code: "BJ", name: "Benin", tz: "Africa/Porto-Novo" },
  { code: "BM", name: "Bermuda", tz: "Atlantic/Bermuda" },
  { code: "BT", name: "Bhutan", tz: "Asia/Thimphu" },
  { code: "BO", name: "Bolivia", tz: "America/La_Paz" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", tz: "America/Curacao" },
  { code: "BA", name: "Bosnia and Herzegovina", tz: "Europe/Sarajevo" },
  { code: "BW", name: "Botswana", tz: "Africa/Gaborone" },
  { code: "BV", name: "Bouvet Island", tz: "UTC" },
  { code: "BR", name: "Brazil", tz: "America/Sao_Paulo" },
  { code: "IO", name: "British Indian Ocean Territory", tz: "Indian/Chagos" },
  { code: "BN", name: "Brunei Darussalam", tz: "Asia/Brunei" },
  { code: "BG", name: "Bulgaria", tz: "Europe/Sofia" },
  { code: "BF", name: "Burkina Faso", tz: "Africa/Ouagadougou" },
  { code: "BI", name: "Burundi", tz: "Africa/Bujumbura" },
  { code: "CV", name: "Cabo Verde", tz: "Atlantic/Cape_Verde" },
  { code: "KH", name: "Cambodia", tz: "Asia/Phnom_Penh" },
  { code: "CM", name: "Cameroon", tz: "Africa/Douala" },
  { code: "CA", name: "Canada", tz: "America/Toronto" },
  { code: "KY", name: "Cayman Islands", tz: "America/Cayman" },
  { code: "CF", name: "Central African Republic", tz: "Africa/Bangui" },
  { code: "TD", name: "Chad", tz: "Africa/Ndjamena" },
  { code: "CL", name: "Chile", tz: "America/Santiago" },
  { code: "CN", name: "China", tz: "Asia/Shanghai" },
  { code: "CX", name: "Christmas Island", tz: "Indian/Christmas" },
  { code: "CC", name: "Cocos (Keeling) Islands", tz: "Indian/Cocos" },
  { code: "CO", name: "Colombia", tz: "America/Bogota" },
  { code: "KM", name: "Comoros", tz: "Indian/Comoro" },
  { code: "CG", name: "Congo", tz: "Africa/Brazzaville" },
  { code: "CD", name: "Congo, Democratic Republic of the", tz: "Africa/Kinshasa" },
  { code: "CK", name: "Cook Islands", tz: "Pacific/Rarotonga" },
  { code: "CR", name: "Costa Rica", tz: "America/Costa_Rica" },
  { code: "CI", name: "Côte d'Ivoire", tz: "Africa/Abidjan" },
  { code: "HR", name: "Croatia", tz: "Europe/Zagreb" },
  { code: "CU", name: "Cuba", tz: "America/Havana" },
  { code: "CW", name: "Curaçao", tz: "America/Curacao" },
  { code: "CY", name: "Cyprus", tz: "Asia/Nicosia" },
  { code: "CZ", name: "Czechia", tz: "Europe/Prague" },
  { code: "DK", name: "Denmark", tz: "Europe/Copenhagen" },
  { code: "DJ", name: "Djibouti", tz: "Africa/Djibouti" },
  { code: "DM", name: "Dominica", tz: "America/Dominica" },
  { code: "DO", name: "Dominican Republic", tz: "America/Santo_Domingo" },
  { code: "EC", name: "Ecuador", tz: "America/Guayaquil" },
  { code: "EG", name: "Egypt", tz: "Africa/Cairo" },
  { code: "SV", name: "El Salvador", tz: "America/El_Salvador" },
  { code: "GQ", name: "Equatorial Guinea", tz: "Africa/Malabo" },
  { code: "ER", name: "Eritrea", tz: "Africa/Asmara" },
  { code: "EE", name: "Estonia", tz: "Europe/Tallinn" },
  { code: "SZ", name: "Eswatini", tz: "Africa/Mbabane" },
  { code: "ET", name: "Ethiopia", tz: "Africa/Addis_Ababa" },
  { code: "FK", name: "Falkland Islands (Malvinas)", tz: "Atlantic/Stanley" },
  { code: "FO", name: "Faroe Islands", tz: "Atlantic/Faroe" },
  { code: "FJ", name: "Fiji", tz: "Pacific/Fiji" },
  { code: "FI", name: "Finland", tz: "Europe/Helsinki" },
  { code: "FR", name: "France", tz: "Europe/Paris" },
  { code: "GF", name: "French Guiana", tz: "America/Cayenne" },
  { code: "PF", name: "French Polynesia", tz: "Pacific/Tahiti" },
  { code: "TF", name: "French Southern Territories", tz: "Indian/Kerguelen" },
  { code: "GA", name: "Gabon", tz: "Africa/Libreville" },
  { code: "GM", name: "Gambia", tz: "Africa/Banjul" },
  { code: "GE", name: "Georgia", tz: "Asia/Tbilisi" },
  { code: "DE", name: "Germany", tz: "Europe/Berlin" },
  { code: "GH", name: "Ghana", tz: "Africa/Accra" },
  { code: "GI", name: "Gibraltar", tz: "Europe/Gibraltar" },
  { code: "GR", name: "Greece", tz: "Europe/Athens" },
  { code: "GL", name: "Greenland", tz: "America/Nuuk" },
  { code: "GD", name: "Grenada", tz: "America/Grenada" },
  { code: "GP", name: "Guadeloupe", tz: "America/Guadeloupe" },
  { code: "GU", name: "Guam", tz: "Pacific/Guam" },
  { code: "GT", name: "Guatemala", tz: "America/Guatemala" },
  { code: "GG", name: "Guernsey", tz: "Europe/London" },
  { code: "GN", name: "Guinea", tz: "Africa/Conakry" },
  { code: "GW", name: "Guinea-Bissau", tz: "Africa/Bissau" },
  { code: "GY", name: "Guyana", tz: "America/Guyana" },
  { code: "HT", name: "Haiti", tz: "America/Port-au-Prince" },
  { code: "HM", name: "Heard Island and McDonald Islands", tz: "UTC" },
  { code: "VA", name: "Holy See", tz: "Europe/Rome" },
  { code: "HN", name: "Honduras", tz: "America/Tegucigalpa" },
  { code: "HK", name: "Hong Kong", tz: "Asia/Hong_Kong" },
  { code: "HU", name: "Hungary", tz: "Europe/Budapest" },
  { code: "IS", name: "Iceland", tz: "Atlantic/Reykjavik" },
  { code: "IN", name: "India", tz: "Asia/Kolkata" },
  { code: "ID", name: "Indonesia", tz: "Asia/Jakarta" },
  { code: "IR", name: "Iran", tz: "Asia/Tehran" },
  { code: "IQ", name: "Iraq", tz: "Asia/Baghdad" },
  { code: "IE", name: "Ireland", tz: "Europe/Dublin" },
  { code: "IM", name: "Isle of Man", tz: "Europe/London" },
  { code: "IL", name: "Israel", tz: "Asia/Jerusalem" },
  { code: "IT", name: "Italy", tz: "Europe/Rome" },
  { code: "JM", name: "Jamaica", tz: "America/Jamaica" },
  { code: "JP", name: "Japan", tz: "Asia/Tokyo" },
  { code: "JE", name: "Jersey", tz: "Europe/London" },
  { code: "JO", name: "Jordan", tz: "Asia/Amman" },
  { code: "KZ", name: "Kazakhstan", tz: "Asia/Almaty" },
  { code: "KE", name: "Kenya", tz: "Africa/Nairobi" },
  { code: "KI", name: "Kiribati", tz: "Pacific/Tarawa" },
  { code: "KP", name: "Korea, Democratic People's Republic of", tz: "Asia/Pyongyang" },
  { code: "KR", name: "Korea, Republic of", tz: "Asia/Seoul" },
  { code: "KW", name: "Kuwait", tz: "Asia/Kuwait" },
  { code: "KG", name: "Kyrgyzstan", tz: "Asia/Bishkek" },
  { code: "LA", name: "Lao People's Democratic Republic", tz: "Asia/Vientiane" },
  { code: "LV", name: "Latvia", tz: "Europe/Riga" },
  { code: "LB", name: "Lebanon", tz: "Asia/Beirut" },
  { code: "LS", name: "Lesotho", tz: "Africa/Maseru" },
  { code: "LR", name: "Liberia", tz: "Africa/Monrovia" },
  { code: "LY", name: "Libya", tz: "Africa/Tripoli" },
  { code: "LI", name: "Liechtenstein", tz: "Europe/Vaduz" },
  { code: "LT", name: "Lithuania", tz: "Europe/Vilnius" },
  { code: "LU", name: "Luxembourg", tz: "Europe/Luxembourg" },
  { code: "MO", name: "Macao", tz: "Asia/Macau" },
  { code: "MG", name: "Madagascar", tz: "Indian/Antananarivo" },
  { code: "MW", name: "Malawi", tz: "Africa/Blantyre" },
  { code: "MY", name: "Malaysia", tz: "Asia/Kuala_Lumpur" },
  { code: "MV", name: "Maldives", tz: "Indian/Maldives" },
  { code: "ML", name: "Mali", tz: "Africa/Bamako" },
  { code: "MT", name: "Malta", tz: "Europe/Malta" },
  { code: "MH", name: "Marshall Islands", tz: "Pacific/Majuro" },
  { code: "MQ", name: "Martinique", tz: "America/Martinique" },
  { code: "MR", name: "Mauritania", tz: "Africa/Nouakchott" },
  { code: "MU", name: "Mauritius", tz: "Indian/Mauritius" },
  { code: "YT", name: "Mayotte", tz: "Indian/Mayotte" },
  { code: "MX", name: "Mexico", tz: "America/Mexico_City" },
  { code: "FM", name: "Micronesia", tz: "Pacific/Pohnpei" },
  { code: "MD", name: "Moldova", tz: "Europe/Chisinau" },
  { code: "MC", name: "Monaco", tz: "Europe/Monaco" },
  { code: "MN", name: "Mongolia", tz: "Asia/Ulaanbaatar" },
  { code: "ME", name: "Montenegro", tz: "Europe/Podgorica" },
  { code: "MS", name: "Montserrat", tz: "America/Montserrat" },
  { code: "MA", name: "Morocco", tz: "Africa/Casablanca" },
  { code: "MZ", name: "Mozambique", tz: "Africa/Maputo" },
  { code: "MM", name: "Myanmar", tz: "Asia/Yangon" },
  { code: "NA", name: "Namibia", tz: "Africa/Windhoek" },
  { code: "NR", name: "Nauru", tz: "Pacific/Nauru" },
  { code: "NP", name: "Nepal", tz: "Asia/Kathmandu" },
  { code: "NL", name: "Netherlands", tz: "Europe/Amsterdam" },
  { code: "NC", name: "New Caledonia", tz: "Pacific/Noumea" },
  { code: "NZ", name: "New Zealand", tz: "Pacific/Auckland" },
  { code: "NI", name: "Nicaragua", tz: "America/Managua" },
  { code: "NE", name: "Niger", tz: "Africa/Niamey" },
  { code: "NG", name: "Nigeria", tz: "Africa/Lagos" },
  { code: "NU", name: "Niue", tz: "Pacific/Niue" },
  { code: "NF", name: "Norfolk Island", tz: "Pacific/Norfolk" },
  { code: "MK", name: "North Macedonia", tz: "Europe/Skopje" },
  { code: "MP", name: "Northern Mariana Islands", tz: "Pacific/Saipan" },
  { code: "NO", name: "Norway", tz: "Europe/Oslo" },
  { code: "OM", name: "Oman", tz: "Asia/Muscat" },
  { code: "PK", name: "Pakistan", tz: "Asia/Karachi" },
  { code: "PW", name: "Palau", tz: "Pacific/Palau" },
  { code: "PS", name: "Palestine, State of", tz: "Asia/Gaza" },
  { code: "PA", name: "Panama", tz: "America/Panama" },
  { code: "PG", name: "Papua New Guinea", tz: "Pacific/Port_Moresby" },
  { code: "PY", name: "Paraguay", tz: "America/Asuncion" },
  { code: "PE", name: "Peru", tz: "America/Lima" },
  { code: "PH", name: "Philippines", tz: "Asia/Manila" },
  { code: "PN", name: "Pitcairn", tz: "Pacific/Pitcairn" },
  { code: "PL", name: "Poland", tz: "Europe/Warsaw" },
  { code: "PT", name: "Portugal", tz: "Europe/Lisbon" },
  { code: "PR", name: "Puerto Rico", tz: "America/Puerto_Rico" },
  { code: "QA", name: "Qatar", tz: "Asia/Qatar" },
  { code: "RE", name: "Réunion", tz: "Indian/Reunion" },
  { code: "RO", name: "Romania", tz: "Europe/Bucharest" },
  { code: "RU", name: "Russian Federation", tz: "Europe/Moscow" },
  { code: "RW", name: "Rwanda", tz: "Africa/Kigali" },
  { code: "BL", name: "Saint Barthélemy", tz: "America/Guadeloupe" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", tz: "Atlantic/St_Helena" },
  { code: "KN", name: "Saint Kitts and Nevis", tz: "America/St_Kitts" },
  { code: "LC", name: "Saint Lucia", tz: "America/St_Lucia" },
  { code: "MF", name: "Saint Martin (French part)", tz: "America/Guadeloupe" },
  { code: "PM", name: "Saint Pierre and Miquelon", tz: "America/Miquelon" },
  { code: "VC", name: "Saint Vincent and the Grenadines", tz: "America/St_Vincent" },
  { code: "WS", name: "Samoa", tz: "Pacific/Apia" },
  { code: "SM", name: "San Marino", tz: "Europe/Rome" },
  { code: "ST", name: "Sao Tome and Principe", tz: "Africa/Sao_Tome" },
  { code: "SA", name: "Saudi Arabia", tz: "Asia/Riyadh" },
  { code: "SN", name: "Senegal", tz: "Africa/Dakar" },
  { code: "RS", name: "Serbia", tz: "Europe/Belgrade" },
  { code: "SC", name: "Seychelles", tz: "Indian/Mahe" },
  { code: "SL", name: "Sierra Leone", tz: "Africa/Freetown" },
  { code: "SG", name: "Singapore", tz: "Asia/Singapore" },
  { code: "SX", name: "Sint Maarten (Dutch part)", tz: "America/Curacao" },
  { code: "SK", name: "Slovakia", tz: "Europe/Bratislava" },
  { code: "SI", name: "Slovenia", tz: "Europe/Ljubljana" },
  { code: "SB", name: "Solomon Islands", tz: "Pacific/Guadalcanal" },
  { code: "SO", name: "Somalia", tz: "Africa/Mogadishu" },
  { code: "ZA", name: "South Africa", tz: "Africa/Johannesburg" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", tz: "Atlantic/South_Georgia" },
  { code: "SS", name: "South Sudan", tz: "Africa/Juba" },
  { code: "ES", name: "Spain", tz: "Europe/Madrid" },
  { code: "LK", name: "Sri Lanka", tz: "Asia/Colombo" },
  { code: "SD", name: "Sudan", tz: "Africa/Khartoum" },
  { code: "SR", name: "Suriname", tz: "America/Paramaribo" },
  { code: "SJ", name: "Svalbard and Jan Mayen", tz: "Europe/Oslo" },
  { code: "SE", name: "Sweden", tz: "Europe/Stockholm" },
  { code: "CH", name: "Switzerland", tz: "Europe/Zurich" },
  { code: "SY", name: "Syrian Arab Republic", tz: "Asia/Damascus" },
  { code: "TW", name: "Taiwan", tz: "Asia/Taipei" },
  { code: "TJ", name: "Tajikistan", tz: "Asia/Dushanbe" },
  { code: "TZ", name: "Tanzania", tz: "Africa/Dar_es_Salaam" },
  { code: "TH", name: "Thailand", tz: "Asia/Bangkok" },
  { code: "TL", name: "Timor-Leste", tz: "Asia/Dili" },
  { code: "TG", name: "Togo", tz: "Africa/Lome" },
  { code: "TK", name: "Tokelau", tz: "Pacific/Fakaofo" },
  { code: "TO", name: "Tonga", tz: "Pacific/Tongatapu" },
  { code: "TT", name: "Trinidad and Tobago", tz: "America/Port_of_Spain" },
  { code: "TN", name: "Tunisia", tz: "Africa/Tunis" },
  { code: "TR", name: "Türkiye", tz: "Europe/Istanbul" },
  { code: "TM", name: "Turkmenistan", tz: "Asia/Ashgabat" },
  { code: "TC", name: "Turks and Caicos Islands", tz: "America/Grand_Turk" },
  { code: "TV", name: "Tuvalu", tz: "Pacific/Funafuti" },
  { code: "UG", name: "Uganda", tz: "Africa/Kampala" },
  { code: "UA", name: "Ukraine", tz: "Europe/Kyiv" },
  { code: "AE", name: "United Arab Emirates", tz: "Asia/Dubai" },
  { code: "GB", name: "United Kingdom", tz: "Europe/London" },
  { code: "US", name: "United States", tz: "America/New_York" },
  { code: "UM", name: "United States Minor Outlying Islands", tz: "Pacific/Wake" },
  { code: "UY", name: "Uruguay", tz: "America/Montevideo" },
  { code: "UZ", name: "Uzbekistan", tz: "Asia/Tashkent" },
  { code: "VU", name: "Vanuatu", tz: "Pacific/Efate" },
  { code: "VE", name: "Venezuela", tz: "America/Caracas" },
  { code: "VN", name: "Viet Nam", tz: "Asia/Ho_Chi_Minh" },
  { code: "VG", name: "Virgin Islands (British)", tz: "America/Tortola" },
  { code: "VI", name: "Virgin Islands (U.S.)", tz: "America/St_Thomas" },
  { code: "WF", name: "Wallis and Futuna", tz: "Pacific/Wallis" },
  { code: "EH", name: "Western Sahara", tz: "Africa/El_Aaiun" },
  { code: "YE", name: "Yemen", tz: "Asia/Aden" },
  { code: "ZM", name: "Zambia", tz: "Africa/Lusaka" },
  { code: "ZW", name: "Zimbabwe", tz: "Africa/Harare" },
];
